<?php
/**
 * Template for default custom entity renderer into set.
 *
 * @var $block \Smile\CustomEntity\Block\Set\Entity\Renderer
 * @var $escaper Magento\Framework\Escaper
 */
?>
<?php
$entity = $block->getEntity();
?>
<div class="product-item-info">
    <a href="<?= $escaper->escapeUrl($block->getEntityUrl()); ?>"?>
        <?= /* @noEscape */ $block->getImage(); ?>
    </a>
    <div class="product details product-item-details">
        <strong class="product name product-item-name">
            <a href="<?= $escaper->escapeUrl($block->getEntityUrl()); ?>">
                <?= $escaper->escapeHtml($entity->getName()) ?>
            </a>
        </strong>
        <div class="product-item-inner">
            <div class="product actions product-item-actions">
                <div class="actions-primary">
                    <a class="action primary" href="<?= $escaper->escapeUrl($block->getEntityUrl()); ?>">
                        <span><?= $escaper->escapeHtml(__('Show detail')) ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
