<?php
/**
 * Attribute set frontend view block
 *
 * @var $block \Smile\CustomEntity\Block\CustomEntity\View
 */
?>
<?php
$customEntity = $block->getEntity();
/** @var \Smile\CustomEntity\Helper\Output $helper */
$helper = $this->helper(\Smile\CustomEntity\Helper\Output::class);
?>
<?php if ($customEntity->getDescription()): ?>
  <div class="custom_entity attribute description">
      <div class="value">
          <?= $helper->customEntityAttribute($customEntity, (string) $customEntity->getDescription(), 'description') ?>
      </div>
  </div>
<?php endif; ?>

<div class="actions">
    <a href="<?= $block->getUrl($customEntity->getAttributeSetUrlKey()) ?>" title="<?= __('Back to %1', $customEntity->getAttributeSet()->getAttributeSetName()) ?>" class="action">
        <?= __('Back') ?>
    </a>
</div>
